# Generated by Django 4.1.6 on 2023-02-07 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('car', models.CharField(max_length=255, unique=True, verbose_name='Car Name')),
                ('color', models.BooleanField(choices=[(0, 'RED'), (1, 'BLUE')], default=0)),
                ('front_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_of_car', to='cars.car')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
