# Generated by Django 4.1.6 on 2023-02-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_front_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
